theme: jekyll-theme-minimal
title: Predictive Modeling for COVID-19 vs. Streptococcal Pneumonia
description: Extending research performed at CU Anschutz into differences between viral and bacterial pneumonia